// automatically generated by the FlatBuffers compiler, do not modify

package ctc;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class Auth extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_2_10(); }
  public static Auth getRootAsAuth(ByteBuffer _bb) { return getRootAsAuth(_bb, new Auth()); }
  public static Auth getRootAsAuth(ByteBuffer _bb, Auth obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public Auth __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String jwt() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer jwtAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer jwtInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public String clientName() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer clientNameAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer clientNameInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }
  public long protocol() { int o = __offset(8); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0L; }

  public static int createAuth(FlatBufferBuilder builder,
      int jwtOffset,
      int clientNameOffset,
      long protocol) {
    builder.startTable(3);
    Auth.addProtocol(builder, protocol);
    Auth.addClientName(builder, clientNameOffset);
    Auth.addJwt(builder, jwtOffset);
    return Auth.endAuth(builder);
  }

  public static void startAuth(FlatBufferBuilder builder) { builder.startTable(3); }
  public static void addJwt(FlatBufferBuilder builder, int jwtOffset) { builder.addOffset(0, jwtOffset, 0); }
  public static void addClientName(FlatBufferBuilder builder, int clientNameOffset) { builder.addOffset(1, clientNameOffset, 0); }
  public static void addProtocol(FlatBufferBuilder builder, long protocol) { builder.addInt(2, (int) protocol, (int) 0L); }
  public static int endAuth(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public Auth get(int j) { return get(new Auth(), j); }
    public Auth get(Auth obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

