// automatically generated by the FlatBuffers compiler, do not modify

package ctc;

@SuppressWarnings("unused")
public final class DeltaKind {
  private DeltaKind() { }
  public static final int PriceLevel = 0;
  public static final int Snapshot = 1;

  public static final String[] names = { "PriceLevel", "Snapshot", };

  public static String name(int e) { return names[e]; }
}

