// automatically generated by the FlatBuffers compiler, do not modify

package ctc;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class ETFCreateRedeemResult extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_2_10(); }
  public static ETFCreateRedeemResult getRootAsETFCreateRedeemResult(ByteBuffer _bb) { return getRootAsETFCreateRedeemResult(_bb, new ETFCreateRedeemResult()); }
  public static ETFCreateRedeemResult getRootAsETFCreateRedeemResult(ByteBuffer _bb, ETFCreateRedeemResult obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public ETFCreateRedeemResult __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long requestId() { int o = __offset(4); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public long etfInstrumentId() { int o = __offset(6); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0L; }
  public long lots() { int o = __offset(8); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public ctc.EtfLeg legs(int j) { return legs(new ctc.EtfLeg(), j); }
  public ctc.EtfLeg legs(ctc.EtfLeg obj, int j) { int o = __offset(10); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int legsLength() { int o = __offset(10); return o != 0 ? __vector_len(o) : 0; }
  public ctc.EtfLeg.Vector legsVector() { return legsVector(new ctc.EtfLeg.Vector()); }
  public ctc.EtfLeg.Vector legsVector(ctc.EtfLeg.Vector obj) { int o = __offset(10); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }
  public boolean success() { int o = __offset(12); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }
  public int rejectCode() { int o = __offset(14); return o != 0 ? bb.getShort(o + bb_pos) & 0xFFFF : 0; }
  public String text() { int o = __offset(16); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer textAsByteBuffer() { return __vector_as_bytebuffer(16, 1); }
  public ByteBuffer textInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 16, 1); }
  public long tsNanos() { int o = __offset(18); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }

  public static int createETFCreateRedeemResult(FlatBufferBuilder builder,
      long requestId,
      long etfInstrumentId,
      long lots,
      int legsOffset,
      boolean success,
      int rejectCode,
      int textOffset,
      long tsNanos) {
    builder.startTable(8);
    ETFCreateRedeemResult.addTsNanos(builder, tsNanos);
    ETFCreateRedeemResult.addLots(builder, lots);
    ETFCreateRedeemResult.addRequestId(builder, requestId);
    ETFCreateRedeemResult.addText(builder, textOffset);
    ETFCreateRedeemResult.addLegs(builder, legsOffset);
    ETFCreateRedeemResult.addEtfInstrumentId(builder, etfInstrumentId);
    ETFCreateRedeemResult.addRejectCode(builder, rejectCode);
    ETFCreateRedeemResult.addSuccess(builder, success);
    return ETFCreateRedeemResult.endETFCreateRedeemResult(builder);
  }

  public static void startETFCreateRedeemResult(FlatBufferBuilder builder) { builder.startTable(8); }
  public static void addRequestId(FlatBufferBuilder builder, long requestId) { builder.addLong(0, requestId, 0L); }
  public static void addEtfInstrumentId(FlatBufferBuilder builder, long etfInstrumentId) { builder.addInt(1, (int) etfInstrumentId, (int) 0L); }
  public static void addLots(FlatBufferBuilder builder, long lots) { builder.addLong(2, lots, 0L); }
  public static void addLegs(FlatBufferBuilder builder, int legsOffset) { builder.addOffset(3, legsOffset, 0); }
  public static int createLegsVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startLegsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addSuccess(FlatBufferBuilder builder, boolean success) { builder.addBoolean(4, success, false); }
  public static void addRejectCode(FlatBufferBuilder builder, int rejectCode) { builder.addShort(5, (short) rejectCode, (short) 0); }
  public static void addText(FlatBufferBuilder builder, int textOffset) { builder.addOffset(6, textOffset, 0); }
  public static void addTsNanos(FlatBufferBuilder builder, long tsNanos) { builder.addLong(7, tsNanos, 0L); }
  public static int endETFCreateRedeemResult(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public ETFCreateRedeemResult get(int j) { return get(new ETFCreateRedeemResult(), j); }
    public ETFCreateRedeemResult get(ETFCreateRedeemResult obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

