// automatically generated by the FlatBuffers compiler, do not modify

package ctc;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class EtfLeg extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_2_10(); }
  public static EtfLeg getRootAsEtfLeg(ByteBuffer _bb) { return getRootAsEtfLeg(_bb, new EtfLeg()); }
  public static EtfLeg getRootAsEtfLeg(ByteBuffer _bb, EtfLeg obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public EtfLeg __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long instrumentId() { int o = __offset(4); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0L; }
  public long lots() { int o = __offset(6); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }

  public static int createEtfLeg(FlatBufferBuilder builder,
      long instrumentId,
      long lots) {
    builder.startTable(2);
    EtfLeg.addLots(builder, lots);
    EtfLeg.addInstrumentId(builder, instrumentId);
    return EtfLeg.endEtfLeg(builder);
  }

  public static void startEtfLeg(FlatBufferBuilder builder) { builder.startTable(2); }
  public static void addInstrumentId(FlatBufferBuilder builder, long instrumentId) { builder.addInt(0, (int) instrumentId, (int) 0L); }
  public static void addLots(FlatBufferBuilder builder, long lots) { builder.addLong(1, lots, 0L); }
  public static int endEtfLeg(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public EtfLeg get(int j) { return get(new EtfLeg(), j); }
    public EtfLeg get(EtfLeg obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

