// automatically generated by the FlatBuffers compiler, do not modify

package ctc;

@SuppressWarnings("unused")
public final class EventType {
  private EventType() { }
  public static final int Heartbeat = 0;
  public static final int Session = 1;
  public static final int Config = 2;

  public static final String[] names = { "Heartbeat", "Session", "Config", };

  public static String name(int e) { return names[e]; }
}

