// automatically generated by the FlatBuffers compiler, do not modify

package ctc;

@SuppressWarnings("unused")
public final class ExecType {
  private ExecType() { }
  public static final int Ack = 0;
  public static final int PartialFill = 1;
  public static final int Fill = 2;
  public static final int CancelAck = 3;
  public static final int ReplaceAck = 4;
  public static final int Reject = 5;

  public static final String[] names = { "Ack", "PartialFill", "Fill", "CancelAck", "ReplaceAck", "Reject", };

  public static String name(int e) { return names[e]; }
}

