// automatically generated by the FlatBuffers compiler, do not modify

package ctc;

@SuppressWarnings("unused")
public final class InstrType {
  private InstrType() { }
  public static final int Equity = 0;
  public static final int ETF = 1;
  public static final int Option = 2;

  public static final String[] names = { "Equity", "ETF", "Option", };

  public static String name(int e) { return names[e]; }
}

