// automatically generated by the FlatBuffers compiler, do not modify

package ctc;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class OrderCancel extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_2_10(); }
  public static OrderCancel getRootAsOrderCancel(ByteBuffer _bb) { return getRootAsOrderCancel(_bb, new OrderCancel()); }
  public static OrderCancel getRootAsOrderCancel(ByteBuffer _bb, OrderCancel obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public OrderCancel __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long clOrdId() { int o = __offset(4); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public long instrumentId() { int o = __offset(6); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0L; }
  public long userId() { int o = __offset(8); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0L; }
  public long teamId() { int o = __offset(10); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0L; }

  public static int createOrderCancel(FlatBufferBuilder builder,
      long clOrdId,
      long instrumentId,
      long userId,
      long teamId) {
    builder.startTable(4);
    OrderCancel.addClOrdId(builder, clOrdId);
    OrderCancel.addTeamId(builder, teamId);
    OrderCancel.addUserId(builder, userId);
    OrderCancel.addInstrumentId(builder, instrumentId);
    return OrderCancel.endOrderCancel(builder);
  }

  public static void startOrderCancel(FlatBufferBuilder builder) { builder.startTable(4); }
  public static void addClOrdId(FlatBufferBuilder builder, long clOrdId) { builder.addLong(0, clOrdId, 0L); }
  public static void addInstrumentId(FlatBufferBuilder builder, long instrumentId) { builder.addInt(1, (int) instrumentId, (int) 0L); }
  public static void addUserId(FlatBufferBuilder builder, long userId) { builder.addInt(2, (int) userId, (int) 0L); }
  public static void addTeamId(FlatBufferBuilder builder, long teamId) { builder.addInt(3, (int) teamId, (int) 0L); }
  public static int endOrderCancel(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public OrderCancel get(int j) { return get(new OrderCancel(), j); }
    public OrderCancel get(OrderCancel obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

