// automatically generated by the FlatBuffers compiler, do not modify

package ctc;

@SuppressWarnings("unused")
public final class OrderType {
  private OrderType() { }
  public static final int Limit = 0;
  public static final int Market = 1;

  public static final String[] names = { "Limit", "Market", };

  public static String name(int e) { return names[e]; }
}

