// automatically generated by the FlatBuffers compiler, do not modify

package ctc;

@SuppressWarnings("unused")
public final class Payload {
  private Payload() { }
  public static final byte NONE = 0;
  public static final byte Auth = 1;
  public static final byte Subscribe = 2;
  public static final byte Unsubscribe = 3;
  public static final byte Heartbeat = 4;
  public static final byte OrderNew = 5;
  public static final byte OrderReplace = 6;
  public static final byte OrderCancel = 7;
  public static final byte CancelAll = 8;
  public static final byte ETFCreateRedeem = 9;
  public static final byte Ack = 10;
  public static final byte Trade = 11;
  public static final byte BookDelta = 12;
  public static final byte PositionUpdate = 13;
  public static final byte ConfigSnapshot = 14;
  public static final byte SessionEvent = 15;
  public static final byte ETFCreateRedeemResult = 16;

  public static final String[] names = { "NONE", "Auth", "Subscribe", "Unsubscribe", "Heartbeat", "OrderNew", "OrderReplace", "OrderCancel", "CancelAll", "ETFCreateRedeem", "Ack", "Trade", "BookDelta", "PositionUpdate", "ConfigSnapshot", "SessionEvent", "ETFCreateRedeemResult", };

  public static String name(int e) { return names[e]; }
}

