// automatically generated by the FlatBuffers compiler, do not modify

package ctc;

@SuppressWarnings("unused")
public final class RejectCode {
  private RejectCode() { }
  public static final int None = 0;
  public static final int SessionClosed = 1;
  public static final int BadSymbol = 2;
  public static final int BadPrice = 3;
  public static final int BadQty = 4;
  public static final int PositionLimit = 5;
  public static final int NotionalLimit = 6;
  public static final int RateLimited = 7;
  public static final int DuplicateClOrdId = 8;
  public static final int UnknownOrder = 9;
  public static final int ReplaceConstraints = 10;
  public static final int CancelConstraints = 11;
  public static final int RiskUnavailable = 12;
  public static final int Unauthorized = 13;

  public static final String[] names = { "None", "SessionClosed", "BadSymbol", "BadPrice", "BadQty", "PositionLimit", "NotionalLimit", "RateLimited", "DuplicateClOrdId", "UnknownOrder", "ReplaceConstraints", "CancelConstraints", "RiskUnavailable", "Unauthorized", };

  public static String name(int e) { return names[e]; }
}

