// automatically generated by the FlatBuffers compiler, do not modify

package ctc;

@SuppressWarnings("unused")
public final class Side {
  private Side() { }
  public static final int Buy = 0;
  public static final int Sell = 1;

  public static final String[] names = { "Buy", "Sell", };

  public static String name(int e) { return names[e]; }
}

