// automatically generated by the FlatBuffers compiler, do not modify

package ctc;

@SuppressWarnings("unused")
public final class StpMode {
  private StpMode() { }
  public static final int None = 0;
  public static final int CancelResting = 1;
  public static final int CancelTaker = 2;
  public static final int DecrementBoth = 3;

  public static final String[] names = { "None", "CancelResting", "CancelTaker", "DecrementBoth", };

  public static String name(int e) { return names[e]; }
}

