// automatically generated by the FlatBuffers compiler, do not modify

package ctc;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class Subscribe extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_2_10(); }
  public static Subscribe getRootAsSubscribe(ByteBuffer _bb) { return getRootAsSubscribe(_bb, new Subscribe()); }
  public static Subscribe getRootAsSubscribe(ByteBuffer _bb, Subscribe obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public Subscribe __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long instruments(int j) { int o = __offset(4); return o != 0 ? (long)bb.getInt(__vector(o) + j * 4) & 0xFFFFFFFFL : 0; }
  public int instrumentsLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }
  public IntVector instrumentsVector() { return instrumentsVector(new IntVector()); }
  public IntVector instrumentsVector(IntVector obj) { int o = __offset(4); return o != 0 ? obj.__assign(__vector(o), bb) : null; }
  public ByteBuffer instrumentsAsByteBuffer() { return __vector_as_bytebuffer(4, 4); }
  public ByteBuffer instrumentsInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 4); }
  public int bookDepth() { int o = __offset(6); return o != 0 ? bb.getShort(o + bb_pos) & 0xFFFF : 0; }
  public boolean trades() { int o = __offset(8); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }
  public boolean positions() { int o = __offset(10); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }
  public long teamId() { int o = __offset(12); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0L; }

  public static int createSubscribe(FlatBufferBuilder builder,
      int instrumentsOffset,
      int bookDepth,
      boolean trades,
      boolean positions,
      long teamId) {
    builder.startTable(5);
    Subscribe.addTeamId(builder, teamId);
    Subscribe.addInstruments(builder, instrumentsOffset);
    Subscribe.addBookDepth(builder, bookDepth);
    Subscribe.addPositions(builder, positions);
    Subscribe.addTrades(builder, trades);
    return Subscribe.endSubscribe(builder);
  }

  public static void startSubscribe(FlatBufferBuilder builder) { builder.startTable(5); }
  public static void addInstruments(FlatBufferBuilder builder, int instrumentsOffset) { builder.addOffset(0, instrumentsOffset, 0); }
  public static int createInstrumentsVector(FlatBufferBuilder builder, long[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addInt((int) data[i]); return builder.endVector(); }
  public static void startInstrumentsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addBookDepth(FlatBufferBuilder builder, int bookDepth) { builder.addShort(1, (short) bookDepth, (short) 0); }
  public static void addTrades(FlatBufferBuilder builder, boolean trades) { builder.addBoolean(2, trades, false); }
  public static void addPositions(FlatBufferBuilder builder, boolean positions) { builder.addBoolean(3, positions, false); }
  public static void addTeamId(FlatBufferBuilder builder, long teamId) { builder.addInt(4, (int) teamId, (int) 0L); }
  public static int endSubscribe(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public Subscribe get(int j) { return get(new Subscribe(), j); }
    public Subscribe get(Subscribe obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

