// automatically generated by the FlatBuffers compiler, do not modify

package ctc;

@SuppressWarnings("unused")
public final class TIF {
  private TIF() { }
  public static final int GFD = 0;
  public static final int IOC = 1;
  public static final int FOK = 2;

  public static final String[] names = { "GFD", "IOC", "FOK", };

  public static String name(int e) { return names[e]; }
}

